CREATE TABLE dbo.ARTIST (
	[ID] INT IDENTITY (1, 1) PRIMARY KEY,
	[FIRSTNAME] VARCHAR(255) NOT NULL,
	[LASTNAME] VARCHAR(255) NOT NULL,
	[DOB] DATETIME NOT NULL
);

CREATE TABLE dbo.ARTWORK (
	[ID] INT IDENTITY (1, 1) PRIMARY KEY,
	[TITLE] VARCHAR(255) NOT NULL,
	[ARTIST] INT FOREIGN KEY REFERENCES dbo.ARTIST(ID)
);

CREATE TABLE dbo.GENRE (
	[ID] INT IDENTITY (1, 1) PRIMARY KEY,
	[NAME] VARCHAR(255) NOT NULL
);

CREATE TABLE dbo.CLASSIFICATION (
	[ID] INT IDENTITY (1, 1) PRIMARY KEY,
	[ARTWORK] INT FOREIGN KEY REFERENCES dbo.ARTWORK(ID) 
);	